### ISSUE TITLE
The formula should be refactored

### ISSUE THREAD

**Issue by genuss** [saltstack-formulas/twemproxy-formula#2]
This formula should have many more states than just build from source and I'm going to make them. Specifically I want to have ``twemproxy.pkg`` and ``twemproxy.config`` states.
So I'd like to propose my contribution here, but I don't know what to do better:
- add new states and leave ``init.sls`` unchanged
- rename ``init.sls`` to ``build.sls`` and make formula by standards, but in this case we lose backwards-compatibity.

Personally I prefer second choice because it doesn't look like formula has many users and packages are already available in repositories (at least for Debian), so building from sources is not a popular solution.
What'd you like me to do? Maybe there is another way to make everybody happy?

**Comment by genuss** [comment]
If someone would be interested I finally got time to open source my personal formula: https://github.com/genuss/twemproxy-formula

**Comment by gravyboat** [comment]
@genuss It appears I wasn't watching this repo closely, sorry for not responding back in January. I prefer the second choice as well. If you want to PR into this one that would work for me, though you might have some naming conflicts in the repos since you need to fork.

**Comment by genuss** [comment]
@gravyboat will do my best to make a PR as soon as I'll get some time!
